@startuml sd-06-mark-fixed-detailed
!include ../_shared/its-uml-style.puml

title Detailed SD 06 - Mark Issue as Fixed
hide footbox

actor "DEV" as Dev
participant ":IssueTrackingSystem" as ISC
participant "targetIssue:Issue" as Issue

Dev -> ISC : changeStatus(issueId, FIXED, comment)

alt 상태 또는 권한 조건이 맞지 않음
  ISC --> Dev : statusChangeRejected(reason)
else 상태 변경 사유가 비어 있음
  ISC --> Dev : statusChangeRejected(commentRequired)
else ASSIGNED -> FIXED 전이가 가능함
  ISC -> Issue : markFixed(currentDev, comment, now)
  activate Issue
  create "fixComment:Comment" as Comment
  Issue --> Comment : new(content=comment,\nwriter=currentDev,\npurpose=STATUS_CHANGE)
  create "commentHistory:IssueHistory" as CommentHistory
  Issue --> CommentHistory : new(COMMENTED, message=comment)
  create "statusHistory:IssueHistory" as StatusHistory
  Issue --> StatusHistory : new(STATUS_CHANGED, ASSIGNED -> FIXED)
  Issue -> Issue : fixer=currentDev;\nstatus=FIXED;\nadd comment/history
  Issue --> ISC : updated(status=FIXED)
  deactivate Issue
  ISC --> Dev : updatedIssue(issueId, status=FIXED)
end

@enduml
