package com.github.marcellokim.issuetracker.setup;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("공개 이력 작성자 표기 정책")
class PublicAttributionPolicyTest {

    @Test
    @DisplayName("공동작성자 trailer가 있는 커밋 메시지를 차단한다")
    void blocksCommitMessageWithCoAuthorTrailer() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Policy update\n\n" + "Co-authored-" + "by: Tool <tool@example.test>\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertNotEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("명시적 AI 생성 attribution 문구가 있는 커밋 메시지를 차단한다")
    void blocksCommitMessageWithExplicitAiAttribution() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Policy update\n\nGenerated by " + "Chat" + "GPT" + "\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertNotEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("도구명만 언급한 커밋 메시지는 허용한다")
    void allowsCommitMessageWithToolNameOnly() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Policy update\n\nReviewed " + "O" + "m" + "X" + " setup notes\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("깨끗한 커밋 메시지는 허용한다")
    void allowsCleanCommitMessage() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, """
                Keep repository authorship policy explicit

                Constraint: Public history must show only human repository contributors.
                Rejected: Tool-specific attribution trailers | they alter public authorship display.
                Confidence: high
                Scope-risk: narrow
                Tested: attribution policy smoke test
                Not-tested: GitHub UI rendering
                """);

        var result = runPolicy("--commit-msg", message.toString());

        assertEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("'Created by Claude' 형태의 attribution 문구를 차단한다")
    void blocksCreatedByClaudeAttribution() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Add feature\n\nCreated by " + "Clau" + "de" + "\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertNotEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("'Written with OpenAI' 형태의 attribution 문구를 차단한다")
    void blocksWrittenWithOpenAiAttribution() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Refactor module\n\nWritten with " + "Open" + "AI" + "\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertNotEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("'Assisted using Anthropic' 형태의 attribution 문구를 차단한다")
    void blocksAssistedUsingAnthropicAttribution() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Update docs\n\nAssisted using " + "Anthro" + "pic" + "\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertNotEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("소문자 'authored by codex' 형태의 attribution 문구를 차단한다")
    void blocksLowercaseAuthoredByCodexAttribution() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Fix bug\n\nauthored by " + "co" + "dex" + "\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertNotEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("'Generated-by:' trailer 형태의 attribution 문구를 차단한다")
    void blocksGeneratedByTrailer() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Update config\n\n" + "Generated-" + "by: automation-tool\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertNotEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("소문자 'generated by chatgpt' 형태의 attribution 문구를 차단한다")
    void blocksLowercaseGeneratedByChatgpt() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Add tests\n\ngenerated by " + "chat" + "gpt" + "\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertNotEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("도구명 없이 'assisted by' 만 있는 커밋 메시지는 허용한다")
    void allowsAssistedByWithoutToolName() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Fix issue\n\nassisted by colleague review\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertEquals(0, result.exitCode(), result.output());
    }

    @Test
    @DisplayName("도구명이 다른 단어 앞에 붙어 있어도 허용한다")
    void allowsToolNameAsWordPrefix() throws IOException, InterruptedException {
        Path message = Files.createTempFile("commit-message", ".txt");
        Files.writeString(message, "Integrate " + "open" + "api" + " client library\n");

        var result = runPolicy("--commit-msg", message.toString());

        assertEquals(0, result.exitCode(), result.output());
    }

    private PolicyResult runPolicy(String... args) throws IOException, InterruptedException {
        String[] command = new String[args.length + 2];
        command[0] = "bash";
        command[1] = "scripts/validate-public-attribution.sh";
        System.arraycopy(args, 0, command, 2, args.length);

        var processBuilder = new ProcessBuilder(command);
        processBuilder.directory(Path.of(".").toAbsolutePath().normalize().toFile());
        processBuilder.redirectErrorStream(true);

        Process process = processBuilder.start();
        String output = new String(process.getInputStream().readAllBytes());
        int exitCode = process.waitFor();

        return new PolicyResult(exitCode, output);
    }

    record PolicyResult(int exitCode, String output) {
    }
}
