@startuml ssd-16-create-account
!include ssd-style.puml
title SSD 16 - UC12 Create Account

actor "Admin" as A
participant ":Issue Tracking System" as S


A -> S: createAccount(loginId, name, password, role)
S --> A: accountCreated(loginId, name, role, isActive=true, confirmation)


@enduml
