@startuml ssd-11-recommend-assignees
!include ssd-style.puml
title SSD 11 - UC8 Recommend Assignment Candidates

actor "PL" as A
participant ":Issue Tracking System" as S


A -> S: startAssignment(issueId)
S --> A: assignmentOptions(devAssigneeCandidates, testerVerifierCandidates, allDevAssignees, allTesterVerifiers)


@enduml
