@startuml ssd-25-remove-dependency
!include ssd-style.puml
title SSD 25 - UC7 Remove Dependency

actor "PL" as A
participant ":Issue Tracking System" as S


A -> S: removeDependency(blockingIssueId, blockedIssueId)
S --> A: dependencyRemoved(blockingIssueId, blockedIssueId, confirmation)


@enduml
