@startuml ssd-17-update-account
!include ssd-style.puml
title SSD 17 - UC12 Update Account

actor "Admin" as A
participant ":Issue Tracking System" as S


alt 계정 이름 변경
  A -> S: renameAccount(loginId, name)
  S --> A: accountRenamed(loginId, name, confirmation)

else 계정 역할 변경
  A -> S: changeAccountRole(loginId, role)
  S --> A: accountRoleChanged(loginId, role, confirmation)
end


@enduml
