@startuml ssd-21-remove-project-member
!include ssd-style.puml
title SSD 21 - UC13 Remove Project Member

actor "Admin" as A
participant ":Issue Tracking System" as S


A -> S: removeProjectParticipant(projectId, loginId)
S --> A: projectParticipantRemoved(projectId, loginId, confirmation)


@enduml
