@startuml ssd-12-delete-issue
!include ssd-style.puml
title SSD 12 - UC9 Delete Closed/New Issue
actor "PL" as A
participant ":Issue Tracking System" as S


A -> S: deleteIssue(issueId, comment)
S --> A: issueDeleted(issueId, status=DELETED, retentionResult)

@enduml
