@startuml ssd-20-add-project-member
!include ssd-style.puml
title SSD 20 - UC13 Add Project Member

actor "Admin" as A
participant ":Issue Tracking System" as S


A -> S: addProjectParticipant(projectId, loginId)
S --> A: projectParticipantAdded(projectId, loginId, confirmation)


@enduml
