@startuml ssd-03-search-issues
!include ssd-style.puml
title SSD 03 - UC3 Search / Browse Issues

actor "Auth User" as A
participant ":Issue Tracking System" as S


A -> S: searchIssues(projectId, issueSearchFilters)
alt 조건 없이 브라우즈
  S --> A: issueList(nonDeletedProjectIssues)
else 조건 검색
  S --> A: issueList(matchingNonDeletedIssues)
end

@enduml
