@startuml ssd-23-edit-issue
!include ssd-style.puml
title SSD 23 - UC15 Edit Issue

actor "Reporter" as A
participant ":Issue Tracking System" as S


A -> S: updateIssue(issueId, title, description)
S --> A: issueUpdated(issueId, title, description, confirmation)


@enduml
