@startuml ssd-19-create-project
!include ssd-style.puml
title SSD 19 - UC13 Create Project

actor "Admin" as A
participant ":Issue Tracking System" as S


A -> S: createProject(name, description)
S --> A: projectCreated(projectId, name, description, confirmation)


@enduml
