@startuml ssd-24-add-dependency
!include ssd-style.puml
title SSD 24 - UC7 Add Dependency

actor "PL" as A
participant ":Issue Tracking System" as S


A -> S: addDependency(blockingIssueId, blockedIssueId)
S --> A: dependencyAdded(dependencyId, blockingIssueId, blockedIssueId, confirmation)


@enduml
