@startuml ssd-18-activate-deactivate-account
!include ssd-style.puml
title SSD 18 - UC12 Activate / Deactivate Account

actor "Admin" as A
participant ":Issue Tracking System" as S


alt 계정 비활성화
  A -> S: deactivateAccount(loginId)
  S --> A: accountDeactivated(loginId, isActive=false, confirmation)

else 계정 활성화
  A -> S: activateAccount(loginId)
  S --> A: accountActivated(loginId, isActive=true, confirmation)
end


@enduml
